### PR TITLE
change packaging to (OSGi) bundle

### PR DESCRIPTION
**Pull request by borcsokj**
pull request is created for the change

### CODE REVIEW

**Comment by borcsokj** [comment]
Create OSGi bundle artifacts instead of plain JAR similar to swagger-core. It is required to use Swagger parser as dependency of Swagger request validator inside Apache Karaf OSGi container installed as feature.

**Comment by woongiap** [comment]
@borcsokj can this be merged already?

**Comment by borcsokj** [comment]
It can be merged but I don't know who can do it/how can I request it.

**Comment by gracekarina** [comment]
@borcsokj @woongiap Thanks for this PR!.
Can you  add a test in OSGi environment?

**Comment by woongiap** [comment]
@gracekarina tested on my local, is that what you meant?

**Comment by borcsokj** [comment]
@gracekarina I also tested changes in OSGi (Apache Karaf) environment. It is not a functional change (that could be covered with unit tests easily) but additional header entries in MANIFEST.MF file of created JAR file.

**Comment by woongiap** [comment]
@gracekarina Hi Grace the change was just making swagger-parser packaging similar to swagger-core and swagger-models, so that it can be used on OSGi environment, can we proceed to merge please?

**Comment by gracekarina** [comment]
Hi, can this be tested with a mock OSCi environment? how do we know for sure that the packaging will behave as expected? Maybe an integration test with embedded OSGi env?

**Comment by woongiap** [comment]
@georgekankava do swagger-core/swagger-mode have similar test?

**Comment by webron** [comment]
@frantuma maybe you have some insight into this one.

**Comment by frantuma** [comment]
@woongiap @borcsokj 

First of all, thank you for this PR. 

Regarding the tests, the idea here is that this is a good moment to add integration tests in OSGi env, as we try to avoid introducing not testable code.

We are aware that this is still the current situation for `swagger-core` but just because we made a mistake before, doesn’t mean we should repeat it.. and providing such tests in the related PR sounds like the best way to do it.

Please let us know if there is a chance anybody out there can indeed add such tests.

**Comment by cvgaviao** [comment]
An osgi manifest is a simple description file that would not require a integration test to it. this PR is taking so long to be merged !

Integration tests on OSGi requires a test framework such as PaxExam. Also it requires a new maven project to hold the integration test code. It is not difficult but has a learning curve and requires time !

Please consider to merge this simple and IMPORTANT change because we (using OSGi) can use swagger-core but unbelievably we can't use swagger-parse easy.  unfortunately, I had to create a bundle to embed the parser v3.

**Pull request merged**
