### PR TITLE
handle `BasicAuthorization` in `SwaggerCompatConverter`

### LINKED ISSUE #120: basicAuth is not handled in `SwaggerCompatConverter`
As I can see, there is a similar `securityDefinition` whose `type` is `basic` in latest swagger(swagger 2.0), but at [here](https://github.com/swagger-api/swagger-parser/blob/18bd0c6a8c990260d0f35c327796199df9b56e7a/modules/swagger-compat-spec-parser/src/main/java/io/swagger/parser/SwaggerCompatConverter.java#L590), both `OAuth2Authorization` and `ApiKeyAuthorization` are handled but nor `BasicAuthorization`.

Is there any reason for which `BasicAuthorization` is ignored?

If none, I will try to fix this problem.

### PR DESCRIPTION
**Pull request by huiyiqun**
try to fix #120 .

Please tell me if there are some existing tests, and I will update tests later.

### CODE REVIEW

**Comment by huiyiqun** [comment]
Why nobody care this?

**Comment by huiyiqun** [comment]
Is there anybody could help me?

**Comment by fehguy** [comment]
Many projects going now so can't always jump on these

**Comment by huiyiqun** [comment]
Thanks

**Comment by fehguy** [comment]
this has been pushed to 1.0.14-SNAPSHOT

**Pull request merged**
