### PR TITLE
Fixes for ExternalRefProcessor issues #434 and #435

### PR DESCRIPTION
**Pull request by leochr**
Fixes 
- #434 - Some $ref values from external files are not updated with the processed internal reference values 
- #435 - Relative reference can also start with "/"

### CODE REVIEW

**Comment by maheshmahadevan** [comment]
Was this fix merged ??

**Comment by gracekarina** [comment]
Hi @leochr, can you please update the branch with master, we merged something similar but not sure if the same. thanks.

**Comment by gracekarina** [comment]
Hi @JehandadK  can you please try on an spec with the new release of parser. I believe we solved this issue, but not sure. Can you please test? if is not solve please send us a PR wit a failing test thanks.

**Comment by gracekarina** [comment]
moved to #864

**Pull request closed without merging**
