### PR TITLE
Fix the problem that the content of extensions cannot be parsed

### PR DESCRIPTION
**Pull request by Bulls1986**
Hello,bro.It seems that the content of extensions under the node is not parsed here,resulting in the extensions content of all nodes not being parsed,so here is added to take the extensions node and parse the content under the node.

### CODE REVIEW

**Comment by Bulls1986** [comment]
This problem will appear in Json format.

**Comment by gracekarina** [comment]
Hi, thanks for the PR, may you please commit the specific change you are making, and a specific test to corroborate the fix, thanks.

**Comment by Bulls1986** [comment]
The new logic is that after the original extensions are parsed, if the content is not parsed, try to parse it again in Json format. I have added the unit test.

**Comment by gracekarina** [comment]
thanks @Bulls1986

**Comment by Msimplehub** [comment]
How  to fix it in 2.0.0-rc1.
and the dependency is :
<dependency>
    <groupId>io.swagger</groupId>
    <artifactId>swagger-parser</artifactId>
    <version>2.0.0-rc1</version>
</dependency>

**Pull request merged**
