### PR TITLE
Added handling for all types of model in ExternalRefProcessor (largel…

### PR DESCRIPTION
**Pull request by samskiter**
…y stolen from ModelProcessor) for #132

This is a thought I had for processing all potential types of models inside a ref

### CODE REVIEW

**Comment by fehguy** [comment]
Can you please add some tests?  I'm trying to do a release of 1.0.13 right now...

**Comment by samskiter** [comment]
I'll try....

**Comment by samskiter** [comment]
Any tips on getting the test running? dependencies or requirements? Only about 7 tests are running with testNG...

**Comment by samskiter** [comment]
Sorry it's too late for me to work this our right now and I'm not familiar with your testing tools...

**Comment by fehguy** [comment]
Hi @samskiter you should be able to run the tests via `mvn test`.

**Pull request closed without merging**
