### PR TITLE
Fix for issue 768 ($ref in external file in requestBody with resolve option true)

### PR DESCRIPTION
**Pull request by ymohdriz**
Hi team,

This PR is to solve the issue '$ref in external file in requestBody with resolve option true' as mentioned in #768 

Please review the PR and merge the same.

Thanks,
Mohammed

### CODE REVIEW

**Comment by jmini** [comment]
This looks good to me. Thank you for your contribution and thank you for adding a test case to the PR.

**Comment by gracekarina** [comment]
@ymohdriz  Hi, Why put '#/' as relative?

**Comment by ymohdriz** [comment]
Hi @gracekarina,

If the reference starts with '#/' then it's internal.
If the reference starts with 'http', then it's url.
if the reference contains '#/' and also not starts with '#/', then it's a relative with the references file. For example, "$ref" : "reference.json#/definitions/sampleSchema" this is relative right?

Thanks,
Mohammed

**Comment by ymohdriz** [comment]
Thanks @gracekarina for merging this commit.

Thanks,
Mohammed

**Pull request merged**
