### PR TITLE
Issue 740: OpenAPI v2 converter: java.lang.IllegalArgumentException with allOf and discriminatorr

### PR DESCRIPTION
**Pull request by ymohdriz**
Hi team,

This PR is to solve the illegal argument exception in swagger converter as mentioned in the issue #740

Please review the PR and merge the same.

Thanks,
Mohammed

### CODE REVIEW

**Comment by jmini** [comment]
Thank you for looking into this topic.

I am not part of the team, but I guess a unit test to cover your changes would be great.

Have a look at [V2ConverterTest](https://github.com/swagger-api/swagger-parser/blob/2.0/modules/swagger-parser-v2-converter/src/test/java/io/swagger/parser/test/V2ConverterTest.java). You will need to add a new file like `issue-740.yaml` in [`swagger-parser-v2-converter/src/test/resources`](https://github.com/swagger-api/swagger-parser/tree/2.0/modules/swagger-parser-v2-converter/src/test/resources) and a new test case in `V2ConverterTest`.

The example (`issue-740.yaml`) should be as small as possible.
Your test should be red before your change and should be green after that.

Let me know if you need some help.

**Comment by jmini** [comment]
This change looks good to me.

@ymohdriz Thank you for this contribution.

I recommend you to add a unit test to this PR. 

As an example, I have created one https://github.com/jmini/swagger-parser/commit/da64e415e9e452e2e1bc5d488373a2a5d20d0e7d in my fork on top of your commit https://github.com/ymohdriz/swagger-parser/commit/e4da4965eaef44bdddb19183545edd4f1fa298ad.

Can you please integrate this commit (or a similar one) in this Pull Request?

---

**Note:** When merging this PR I recommend "Squash and merge" because the intermediate commit in this branch are not really useful.

**Comment by ralphdoe** [comment]
Like @jmini pointed. I think it might be a good idea to add the test.

**Comment by ymohdriz** [comment]
Hi @ralphdoe,

Sure I will add the junit test for this issue. In future, I will commit the junits along with the fix.

Thanks,
Mohammed

**Comment by jmini** [comment]
This PR has still no junit tests...

@ymohdriz feel free to just add my commit to your PR or to add something similar. 
Thank you in advance.

**Pull request merged**
