### PR TITLE
Fix bug in relative path generation: 

### PR DESCRIPTION
**Pull request by samanthacatania**
'./' results in array out of bounds ands '../' results in root component not being truncated properly

### CODE REVIEW

**Comment by fehguy** [comment]
Can you please add a test to reproduce this issue?

**Comment by samanthacatania** [comment]
I added tests and simplified the code a bit. However I found an issue with nested relative paths. I'' try to figure out how to fix it.

**Comment by samanthacatania** [comment]
Opened the following issue #355

**Comment by fehguy** [comment]
Please use master.  The develop branch has drifted a bunch and will be deleted.

**Pull request closed without merging**
