### PR TITLE
Fix for 749

### PR DESCRIPTION
**Pull request by ymohdriz**
Hi team,

This PR is to solve the issue '$ref in external file in parameter with resolve option true' as mentioned in https://github.com/swagger-api/swagger-parser/issues/749

Please review the PR and merge the same.

Thanks,
Mohammed

### CODE REVIEW

**Comment by jmini** [comment]
This change looks good to me.

@ymohdriz Thank you for this contribution.

I recommend you to add a unit test to this PR. 

As an example, I have created one https://github.com/jmini/swagger-parser/commit/a2c4abe25bb45eb065a2112d0c88cc5b8ee775d3 in my fork on top of your commit https://github.com/ymohdriz/swagger-parser/commit/94910e5a3bb2d2fe988c6d1b495c154b207f597e.

It is simple: I have extended a test specification I found in the repository with a parameter case as described in #749.

Without your fix the test is red, with your fix it is green.

Can you please integrate this commit (or a similar one) in this Pull Request?

**Comment by gracekarina** [comment]
Hi @ymohdriz can you please add a unit test for it. Thanks!

**Comment by ymohdriz** [comment]
Hi @gracekarina ,

I have committed the junit tests fot this issue.

Thanks a lot for your help @jmini 

Thanks,
Mohammed

**Comment by gracekarina** [comment]
Thanks @ymohdriz  and @jmini

**Pull request merged**
