### PR TITLE
refs #152 #125 - handle 'file' URL scheme

### PR DESCRIPTION
**Pull request by frantuma**
@fehguy
References #152 and #125, updating Paths.get calls in case of file scheme in URL, supporting absolute urls with file scheme. 

It doesn't implement a comprehensive solution for location/URI management but it basically stays on safe side converting backslashes and using URI.create().

Build tested on Windows.

### CODE REVIEW

**Comment by fehguy** [comment]
@garydgregory does this fix your issue?

**Comment by garydgregory** [comment]
Nope:

    @Test // fails
    public void readFileAbsoluteUri1() {
        final SwaggerParser parser = new SwaggerParser();
        final Swagger swagger = parser.read(
                "file:///E:/vcs/git/swagger-api/swagger-parser/modules/swagger-parser/src/test/resources/thing.json");
        assertNotNull(swagger);
    }

    @Test // passes
    public void readFileAbsoluteUri2() {
        final SwaggerParser parser = new SwaggerParser();
        final Swagger swagger = parser.read(
                "E:\\vcs\\git\\swagger-api\\swagger-parser\\modules\\swagger-parser\\src\\test\\resources\\thing.json");
        assertNotNull(swagger);
    }

    @Test // fails, same as #1
    public void readFileAbsoluteUri3() {
        final SwaggerParser parser = new SwaggerParser();
        final Swagger swagger = parser.read(Paths
                .get("E:\\vcs\\git\\swagger-api\\swagger-parser\\modules\\swagger-parser\\src\\test\\resources\\thing.json")
                .toUri().toString());
        assertNotNull(swagger);
    }

**Comment by garydgregory** [comment]
This would be a lot simpler if the API had a read(Path) and a read(URI) method:

new SwaggerParser().read(new URI(...));
new SwaggerParser().read(Paths.get(...));

**Comment by frantuma** [comment]
@garydgregory  I agree having overloaded read() with Path or Uri would help and we could add them; however original issue with String version would not be solved; also here I am not sure, I have tested locations in the form file:///X:/nnn/thing.json and X:\nnn\thing.json in a Win 8 Java 7-8 environment and they work correctly; is it failing for you builiding this PR code? and in which environment?

**Comment by garydgregory** [comment]
I built with:

- git master 
- Windows 7 Professional 64-bit
- Oracle JDK 1.7.0_79 64-bit
- Eclipse 4.5.1
- Added to modules/swagger-parser/src/test/java/io/swagger/parser/SwaggerReaderTest.java

Swagger tries to load "\E:\and\so\on\swagger.json", notice the leading "\".

**Comment by frantuma** [comment]
PR has not been yet merged into master, can you try fetching https://github.com/frantuma/swagger-parser/tree/issue-152 branch?

**Comment by fehguy** [comment]
@garydgregory I'm going to merge this so you can verify against master.

**Comment by garydgregory** [comment]
Hi,

OK, that works. Thank you!

Are the unit tests sufficient?

When can we expect to see this fix in a release?

Thank you,
Gary

**Comment by fehguy** [comment]
Should be a release this week (maybe today?).  Yes, I think the tests are sufficient.  Thanks!

**Pull request merged**
