### PR TITLE
PR for swagger-api/swagger-parser#39

### PR DESCRIPTION
**Pull request by RobWin**
SwaggerCompatConverter method is not implemented yet.

### CODE REVIEW

**Comment by fehguy** [comment]
The compat converter support isn't easily done since swagger 1.2 specs typically live in multiple files.

**Comment by RobWin** [comment]
Do you accept the PR then?

**Comment by fehguy** [comment]
Suggest you throw an exception as "not implemented" for 1.2 instead of failing silently then I can merge.

**Comment by RobWin** [comment]
Shall I remove the new method from SwaggerParser then, if it is not supported for Swagger 1.2?
And just leave it in Swagger20Parser?

**Comment by RobWin** [comment]
New method does not invoke other extensions except Swagger20Parser now.
It only supports swagger 2.0

**Comment by RobWin** [comment]
@fehguy ? :-)

**Comment by fehguy** [comment]
apologies for the delay

**Comment by RobWin** [comment]
Thx

**Pull request merged**
