### PR TITLE
primitive schemas are no longer lost in conversion

### PR DESCRIPTION
**Pull request by bedag-moo**
Fixes https://github.com/swagger-api/swagger-codegen/issues/1241

### CODE REVIEW

**Comment by fehguy** [comment]
Hi @bedag-moo can you please supply a test for this?

**Comment by bedag-moo** [comment]
The best test would probably be an integration test with swagger-codegen, but I don't see any infrastructure for automating such tests in swagger-parser? What kind of test are you looking for?

**Comment by fehguy** [comment]
Typically when using codegen, there is a json or yaml specification file, which is run through the parser, that has some situation that the parser doesn't like.  In the case of this PR, I'd like to see a small specification with a broken behavior which is fixed by this PR.  Then we know precisely what was causing the issue, and are protected against it happening again.  So my guess is that your specification file will be enough for us to figure out what to test.  Can you share it here or in private?

**Comment by bedag-moo** [comment]
@fehguy, do you need anything else from me so you can merge this?

**Comment by fehguy** [comment]
Well, your spec may exhibit the issue, but until there's an automated unit test we can't merge this.  So it can be done faster by you, or you can wait for us to do it.

**Comment by bedag-moo** [comment]
Here you go.

**Comment by fehguy** [comment]
Thank you

**Pull request merged**
