### PR TITLE
Fix handling of relative refs without leading dot

### LINKED ISSUE #421: Relative refs in parameters and schema are not resolved correctly
If the value of a $ref is a relative reference but does not start with ".", the swagger core (specifically `GenericRef`) treats it as an internal ref.  E.g.
```
"$ref" : "./path/to/model.json#/thing"
```
is treated as a relative URI but 
```
"$ref": "path/to/model.json#/thing"
```
is treated as internal.

According to #306, this is intentional behavior in swagger core:
> we added a convenience for a 1.2-style spec, where references did not need the full anchor. 

So the parser needs to account for this by transforming _actual_ relative refs into something that swagger-core will not try to treat as an internal ref.

The fix for #306 added code to make this transformation to relative refs that appear in properties.  The same fix is needed for parameters and schema.

### PR DESCRIPTION
**Pull request by mkistler**
Fixes #421

### CODE REVIEW

**Comment by mkistler** [comment]
Okay ... this is harder than I thought.  This code breaks on regular internal refs (starting with a "#").  I will rework and update this PR.

**Comment by mkistler** [comment]
Rework is complete and I've added tests to catch the errors I missed in the earlier commits.  I think this is ready for review now.

**Comment by mkistler** [comment]
@fehguy  What needs to be done to move this forward?

**Comment by fehguy** [comment]
Your fix looks good, I need more time to verify.

**Comment by mkistler** [comment]
Any update on this?

**Comment by gracekarina** [comment]
@mkistler Thanks for this PR! sorry for the delay.

**Pull request merged**
