### PR TITLE
Don't configure the parent with allOf

### LINKED ISSUE #245: With a composed model (allOf), only set the model which holds a discriminator field as parent
As per swagger spec's definition of [allOf](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#composition-and-inheritance-polymorphism), inheritance should only be used in the case the parent model has a discriminator field.
The current implementation is to set the first model as parent but this results in issues with generated code (see https://github.com/swagger-api/swagger-codegen/issues/2096)

### PR DESCRIPTION
**Pull request by cbornet**
Fix #245

### CODE REVIEW

**Comment by jeff9finger** [comment]
+1

**Comment by cbornet** [comment]
rebased to resolve conflict.

**Comment by cbornet** [comment]
@fehguy Thanks for merging :+1: !
Any chance to see a release soon ? This would allow to fix the Java inheritance issues in swagger-codegen !

**Comment by fehguy** [comment]
@cbornet very close, this is required for the codegen release, which we (and you!) are working on.

**Pull request merged**
