### PR TITLE
Issue-1899: Fix to allow both snakeyaml 1.33 and 2.0 to work properly

### PR DESCRIPTION
**Pull request by cmuchinsky**
Fixes https://github.com/swagger-api/swagger-parser/issues/1899

### CODE REVIEW

**Comment by AlexandrosMor** [comment]
Here I am tagging the swagger-api members to review the pr @char0n @frantuma @gracekarina @HugoMario @ponelat 
Good job @cmuchinsky !

**Comment by cmuchinsky** [comment]
Closing as https://github.com/swagger-api/swagger-parser/commit/27a690e91017780156dd1f3015348e4eac93b044 appears to take care of it

**Comment by oscarsan** [comment]
@cmuchinsky  in which way [27a69e](https://github.com/swagger-api/swagger-parser/commit/27a690e91017780156dd1f3015348e4eac93b044) is fixing the issue? I still have the error when forcing snake-2.0 on io.swagger.parser.v3:swagger-parser 2.0.5.

**Comment by cmuchinsky** [comment]
> @cmuchinsky in which way [27a69e](https://github.com/swagger-api/swagger-parser/commit/27a690e91017780156dd1f3015348e4eac93b044) is fixing the issue? I still have the error when forcing snake-2.0 on io.swagger.parser.v3:swagger-parser 2.0.5
> 
> `java.lang.NoSuchMethodError: 'void org.yaml.snakeyaml.parser.ParserImpl.<init>(org.yaml.snakeyaml.reader.StreamReader)`

you must upgrade to swagger-parser 2.1.13

**Pull request closed without merging**
