### PR TITLE
Fix NPE for the operations, which accept all methods

### PR DESCRIPTION
**Pull request by daivanov**
In my REST application I have mapping, which serves as 404 page and it accepts all HTTP methods:
@RequestMapping(value=MISSING_CALL, produces=MediaType.APPLICATION_JSON_VALUE)

Parser cannot handle it properly:
Exception in thread "main" java.lang.NullPointerException
	at io.swagger.parser.SwaggerCompatConverter.convert(SwaggerCompatConverter.java:481)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:111)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:34)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:87)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)

### CODE REVIEW

**Comment by webron** [comment]
@daivanov - thanks, but the development is done in the develop_2.0 branch. Can you resubmit against that please?

**Comment by daivanov** [comment]
After switching to develop_2.0 in swagger-codegen I'm getting the following exception with the same command was working fine in master. Did syntax or format change?

$ java -jar modules/swagger-codegen-cli/target/swagger-codegen-cli.jar generate   -i http://localhost:8080/MWA/api-docs/   -l html   -o xxx
reading from http://localhost:8080/MWA/api-docs/
java.io.IOException: Server returned HTTP response code: 406 for URL: http://localhost:8080/MWA/api-docs/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:88)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:27)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:25)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:76)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)
Server returned HTTP response code: 406 for URL: http://localhost:8080/MWA/api-docs/
reading from http://localhost:8080/MWA/api-docs/
java.io.IOException: Server returned HTTP response code: 406 for URL: http://localhost:8080/MWA/api-docs/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:88)
	at io.swagger.parser.Swagger20Parser.read(Swagger20Parser.java:27)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:34)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:76)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)
Server returned HTTP response code: 406 for URL: http://localhost:8080/MWA/api-docs/
java.io.IOException: Server returned HTTP response code: 406 for URL: http://localhost:8080/MWA/api-docs/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:88)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:116)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:53)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:34)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:76)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)
java.io.IOException: Server returned HTTP response code: 406 for URL: http://localhost:8080/MWA/api-docs/
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1627)
	at io.swagger.parser.util.RemoteUrl.urlToString(RemoteUrl.java:88)
	at io.swagger.parser.SwaggerCompatConverter.readResourceListing(SwaggerCompatConverter.java:116)
	at io.swagger.parser.SwaggerCompatConverter.read(SwaggerCompatConverter.java:53)
	at io.swagger.parser.SwaggerParser.read(SwaggerParser.java:34)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:76)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)
Exception in thread "main" java.lang.RuntimeException: missing swagger input!
	at com.wordnik.swagger.codegen.DefaultGenerator.generate(DefaultGenerator.java:54)
	at com.wordnik.swagger.codegen.cmd.Generate.run(Generate.java:77)
	at com.wordnik.swagger.codegen.SwaggerCodegen.main(SwaggerCodegen.java:33)

**Comment by webron** [comment]
If the server returned 406 that has nothing to do with the codegen...

**Comment by daivanov** [comment]
When I use codegen from master server (obviously I have only one server) returns 200.

**Comment by webron** [comment]
Perhaps there's a different bug with regards to the headers being sent.

**Comment by daivanov** [comment]
Master seems to send the following accept header:
Accept: text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2

And develop_2.0 uses:
Accept: application/json, application/yaml, *.*

This is the only difference, but application/json should be fine.

**Comment by webron** [comment]
If it sends `Accept: application/json, application/yaml, .` exactly (with the `, .` at the end) then that may be a problem (and you should open a separate issue on it on swagger-codegen).

Otherwise, there may be a problem with your server that it doesn't recognize the requested mime types. How do you serve your api-docs?

**Comment by daivanov** [comment]
Ok,I reported https://github.com/swagger-api/swagger-codegen/issues/721. Thank you.

**Comment by fehguy** [comment]
From the comments, I think this isn't needed so I'm closing it.  Please reopen if needed.

**Pull request closed without merging**
