### PR TITLE
Make external relative refs work

### PR DESCRIPTION
**Pull request by samskiter**
This is a WIP that you are welcome to make additions to. I'm not sure how far I'll be able to get to getting all the tests working but I think the core idea is there. See https://github.com/swagger-api/swagger-parser/issues/135

### CODE REVIEW

**Comment by samskiter** [comment]
Hello, is it worth continuing this PR? Is it something you want?

**Comment by fehguy** [comment]
I don't know what the goal is here other than making relative refs work.  It also fails the tests, so I don't really know what state the PR is in?

**Comment by samskiter** [comment]
The aim is to make relative references work yes.

The state is that the non-test code has no compile errors and should be approximately correct (obviously tests should reveal errors). I have yet to get round to finish updating all the test cases - they will take me some time though so if you could look over what I have so far and say if you'd like me to continue or approach the problem differently...

**Comment by fehguy** [comment]
This has been addressed in https://github.com/swagger-api/swagger-parser/commit/f4bb680744a79402fe1f737a1bad569cb045a5e4

**Pull request closed without merging**
