### PR TITLE
upgrade to JUnit 4.13 RC1

### PR DESCRIPTION
**Pull request by sullis**
- this is the latest release of JUnit4

### CODE REVIEW

**Comment by gracekarina** [comment]
Hi, thanks for the PR, we are going to keep using the stable version.

**Comment by sullis** [comment]
obsolete.

**Comment by gracekarina** [comment]
what about 4.12.x?

**Comment by sullis** [comment]
JUnit 4.13.x is expected to be released very soon

https://github.com/junit-team/junit4/issues/1496

**Comment by gracekarina** [comment]
ok no problem then, we'll wait.

**Pull request closed without merging**
