### PR TITLE
#514 fixing composed schema parsing

### LINKED ISSUE #514: Parsing allOf, anyOf and oneOf does not return all the elements of these arrays with OAS 3.0.0
Hello,

parsing a OAS 3.0.0 spec with this configuration :
```yaml
openapi: '3.0'
components:
  schemas:
    Pet:
      type: object
      required:
      - pet_type
      properties:
        pet_type:
          type: string
    Cat:
      allOf:
      - $ref: '#/components/schemas/Pet'
      - type: object
        # all other properties specific to a `Cat`
        properties:
          name:
            type: string
```

Then the `Cat` object contains only 1 element : the last one.

The bug is in `io.swagger.parser.v3.util.OpenAPIDeserializer` class, in the `getSchema` method. allOf, anyOf and oneOf nodes are not well managed.

```java
        if(allOfArray != null) {

            for(JsonNode n : allOfArray) {
                if(n.isObject()) {
                    ComposedSchema allOfList = new ComposedSchema();
                    schema = getSchema((ObjectNode) n,location,result);
                    allOfList.addAllOfItem(schema);
                    schema = allOfList;
                }
            }
        }
```
should be 
```java
        if(allOfArray != null) {
            ComposedSchema allOfList = new ComposedSchema();
            for(JsonNode n : allOfArray) {
                if(n.isObject()) {
                    schema = getSchema((ObjectNode) n,location,result);
                    allOfList.addAllOfItem(schema);
                }
            }
            schema = allOfList;
        }
```

And same thing for anyOf and oneOf

### PR DESCRIPTION
**Pull request by phiz71**
Fix #514 
added a test for each composedSchema

### CODE REVIEW

**Comment by gracekarina** [comment]
Thank you! @phiz71

**Comment by webron** [comment]
@phiz71 sorry, should have merged in order. Can you resolve the conflict and then I'll merge?

**Comment by phiz71** [comment]
Done

**Comment by webron** [comment]
Thanks, @phiz71!

**Pull request merged**
