### PR TITLE
Fix for issue 758

### PR DESCRIPTION
**Pull request by ymohdriz**
Hi team,

This PR is to solve the issue 'OpenAPI v2 Converter: NPE when 'enum' field is available and 'type' field is missing in query parameter' as mentioned in #758 

Please review the PR and merge the same.

Thanks,
Mohammed

### CODE REVIEW

**Comment by jmini** [comment]
This change looks good to me.

@ymohdriz Thank you for this contribution.

I recommend you to add a unit test to this PR. 

As an example, I have created one https://github.com/jmini/swagger-parser/commit/0777e397c9039a639f0956d01efe9ede56d1214f in my fork on top of your commit https://github.com/ymohdriz/swagger-parser/commit/45f76e1c5931394ed8a38065496d3fdf58aa8f9b.

It is simple: I have taken the example you have put in issue #758 and I add it as a new file: ` modules/swagger-parser-v2-converter/src/test/resources/issue-758.json` in the project. Then I have create a small test case (a new method) in the `V2ConverterTest` class that open the file and perform some assertion.

Without your fix I get the `NullPointerException`. With your fix I do not.

Can you please integrate this commit (or a similar one) in this Pull Request?

**Comment by ymohdriz** [comment]
Hi @jmini,

Thanks for your help.
In future, I will commit the changes along with the junit test.

Thanks,
Mohammed

**Comment by ralphdoe** [comment]
Great Work @ymohdriz!

**Comment by jmini** [comment]
@ralphdoe thank you for merging this!

**Comment by ralphdoe** [comment]
Thanks to you @jmini!

**Pull request merged**
