### PR TITLE
Fix referenced models parsing on definitions

### PR DESCRIPTION
**Pull request by tzimisce012**
Fix issue #494

### CODE REVIEW

**Comment by tzimisce012** [comment]
Would it be possible to merge this branch with master? It is important to fix some problems in the swagger codegen for JavaPlayFramework

**Comment by webron** [comment]
Thanks for the PR. Can you add a test to it?

**Comment by tzimisce012** [comment]
I just added the test

**Comment by tzimisce012** [comment]
any advances?

**Comment by palmerabollo** [comment]
I'm also interested in it.

**Comment by palmerabollo** [comment]
@fehguy do you plan to publish a new release anytime soon?

**Comment by edrevo** [comment]
ping @fehguy about getting a new release. this is a critical fix for us.

**Pull request merged**
