### PR TITLE
enable STRICT_DUPLICATE_DETECTION in Jackson parser

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
Ready for review.

**Comment by sullis** [comment]
WDYT? @gracekarina @frantuma

**Comment by gracekarina** [comment]
Hi @sullis Thanks for this PR, I have to test this with the dependant projects before merging.

**Comment by sullis** [comment]
Let me know if I need to write additional unit tests. I am happy to contribute. @gracekarina

**Comment by sullis** [comment]
@gracekarina  when do you plan to release [swagger-parser] 2.0.17?

**Comment by gracekarina** [comment]
Hi, probably mid january

**Comment by jmini** [comment]
See the same change for Yaml parser: #1313

**Pull request merged**
